### ISSUE TITLE
Adding  a third-party library to the plugin .

### ISSUE THREAD

**Issue by tareq2** [molsonkiko/NppCSharpPluginPack#5]
As I am trying to add a reference to a third-party library to this template I copied this DLL to the plugin directory, but it gives me the error "could not load file or assembly...the system could not find this file" is adding a library possible and how can it be done?

**Comment by molsonkiko** [comment]
Have you tried using [NuGet](https://www.nuget.org/)?

As far as I know, if you just go to `Project->Manage NuGet Packages...` from the Visual Studio main menu, you can just include a new package in the project. If you go to that tab in Visual Studio, you will see that the `UnmanagedExports.Repack.Upgrade` package is included with the plugin by default, because it is needed to allow the plugin to work with Notepad++.

Let me know if this helps. If you still can't, it may be because you're using an old version of the template, and you should use the most up-to-date source code instead.

**Comment by tareq2** [comment]
Yes I am using a nuget package 
![image](https://github.com/molsonkiko/NppCSharpPluginPack/assets/375528/05ff3db9-82f7-48c8-b4f7-fad34fa68319)

**Comment by rdipardo** [comment]
> I copied this DLL to the plugin directory

I'm afraid that's not going to work. The .NET runtime doesn't treat the current directory as an implicit load path. The plugin needs to resolve the assembly path and pass it to the [`System.Reflection.Assembly.Load` method][0].

Here's a link to an expert's advice on how to do that: <https://github.com/oleg-shilo/cs-script.npp/issues/66#issuecomment-1086657272>

[0]:https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load

**Comment by tareq2** [comment]
I have added the following code to the main.cs file and it worked  
```

 static Assembly LoadFromSameFolder(object sender, ResolveEventArgs args)
 {
     //to load dlls  from plugin folder
     string folderPath = Path.Combine(Npp.notepad.GetNppPath(),  PluginName); //Npp.notepad.GetNppPath() = ""
     folderPath = Path.Combine("C:\\Program Files\\Notepad++", PluginName);
     string assemblyPath = Path.Combine(folderPath, new AssemblyName(args.Name).Name + ".dll");

     if (!File.Exists(assemblyPath)) return null;
     Assembly assembly = Assembly.LoadFrom(assemblyPath);
     return assembly;
 }
 static internal void CommandMenuInit()
 {

     AppDomain currentDomain = AppDomain.CurrentDomain;
     currentDomain.AssemblyResolve += new ResolveEventHandler(LoadFromSameFolder);
```

I don't know if there is a better place to handle this or not,
Also i wonder why the Npp.notepad.GetNppPath() is  empty  here.

**Comment by molsonkiko** [comment]
My most recent commit (discussed in [this section of docs/README.md](https://github.com/molsonkiko/NppCSharpPluginPack/blob/main/docs/README.md#loading-third-party-dependencies)) should allow users of the template to use NuGet packages without doing anything besides installing them, and other locally installed DLL's without too much work.

I'd appreciate if people could test this commit, to test it with different kinds of dependencies. I've only tested it building for Notepad++ 8.6.4, and I haven't tried targeting a portable Notepad++ installation.

Many thanks to both @rdipardo  and @tareq2 for your help on this issue. This has significantly expanded my own knowledge of C#, and I believe it will make the template a lot more useful for others.

**Comment by molsonkiko** [comment]
Nobody has complained about how the plugin pack handles dependencies, and I still haven't seen any issues, so I'm closing this issue.
