### ISSUE TITLE
"This ANSI plugin is not compatible with your Unicode Notepad++" error

### ISSUE THREAD

**Issue by cdellafera** [molsonkiko/NppCSharpPluginPack#6]
I cloned the repository and rebuilt it in VS. When I launch NPP it throws the error "CSharpPluginPack.dll is not compatible with the current version of Notepad++." I'm running NP++ 64-bit v8.6.9. Not sure where to go from here. Any on-line references to this error seems to be from 2019!

**Comment by molsonkiko** [comment]
There are two main possibilities that occur to me:
1. You are building the 32-bit version of the plugin and copying it into the `plugins` folder of your 64-bit Notepad++. This seems unlikely, because Notepad++ would be expected to give a different error message in that situation.
2. Some runtime error is happening as you load the plugin. I recommend building in Debug mode and setting breakpoints at the start of the [`Main.CommandMenuInit()` method](https://github.com/molsonkiko/NppCSharpPluginPack/blob/82edb829a39426d1a2cba8d7fb6284fc07267c5c/NppCSharpPluginPack/Main.cs#L68) and [`SettingsBase(bool)` method](https://github.com/molsonkiko/NppCSharpPluginPack/blob/82edb829a39426d1a2cba8d7fb6284fc07267c5c/NppCSharpPluginPack/PluginInfrastructure/SettingsBase.cs#L71), since those are two of the first methods called when the plugin starts up. If the error happens before any of those breakpoints are hit, I'm not really sure what is happening.

I've definitely seen error messages like that before, but it's been a long time since I last saw one, and I can't remember how I fixed it.

Could you share your full debug info (`?-Debug Info...` from the Notepad++ main menu)? That might help us diagnose the source of the issue.

**Comment by cdellafera** [comment]
The dependencies folder has an x64 file so it seems unlikely I downloaded the wrong version. I tried setting the debug breakpoints, but the error occurs before then, so something is odd. This is definitely only due to this plugin. The error message references the plugin by name and removing it allows NPP to launch normally. Here's the debug information: Notepad++ v8.6.9 (64-bit) Build time : Jul 12 2024 - 05:09:25 Path : C:\Program Files\Notepad++\notepad++.exe Command Line : Admin mode : OFF Local Conf mode : OFF Cloud Config : OFF Periodic Backup : ON OS Name : Windows 10 Pro (64-bit) OS Version : 22H2 OS Build : 19045.4651 Current ANSI codepage : 1252 Plugins : BracketsCheck (1.2.2) DSpellCheck (1.5) Explorer (1.9.9) JsonTools (8) mimeTools (3.1) NppConverter (4.6) NppExport (0.4) PoorMansTSqlFormatterNppPlugin (1.6.13.31508) XMLTools (3.1.1.13) The AssemblyInfo.cs is: using System.Reflection; using System.Runtime.InteropServices; // General Information about an assembly is controlled through the following // set of attributes. Change these attribute values to modify the information // associated with an assembly. [assembly: AssemblyTitle("C# Demo plugin for Notepad++")] [assembly: AssemblyDescription("")] [assembly: AssemblyConfiguration("")] [assembly: AssemblyCompany("Mark Johnston Olson")] [assembly: AssemblyProduct("C# Demo plugin for Notepad++")] [assembly: AssemblyCopyright("Copyright © molsonkiko 2024")] [assembly: AssemblyTrademark("")] [assembly: AssemblyCulture("")] // Setting ComVisible to false makes the types in this assembly not visible // to COM components. If you need to access a type in this assembly from // COM, set the ComVisible attribute to true on that type. [assembly: ComVisible(false)] // The following GUID is for the ID of the typelib if this project is exposed to COM [assembly: Guid("2f8c343a-3fa0-47ba-b3b5-23a5757f8779")] // Version information for an assembly consists of the following four values: // // Major Version // Minor Version // Build Number // Revision // [assembly: AssemblyVersion("0.0.3.11")] [assembly: AssemblyFileVersion("0.0.3.11")] Ciarán... Ciarán Anthony DellaFera, BSG, M.D. 99 Otis Street, Apt 4 Cambridge, MA 02141-1722 Mobile: +1 617.921.0682 Pronouns: He/Him/His On Aug 10, 2024, at 4:01 PM, molsonkiko ***@***.***> wrote: There are two main possibilities that occur to me: You are building the 32-bit version of the plugin and copying it into the plugins folder of your 64-bit Notepad++. This seems unlikely, because Notepad++ would be expected to give a different error message in that situation. Some runtime error is happening as you load the plugin. I recommend building in Debug mode and setting breakpoints at the start of the Main.CommandMenuInit() method and SettingsBase(bool) method , since those are two of the first methods called when the plugin starts up. If the error happens before any of those breakpoints are hit, I'm not really sure what is happening. I've definitely seen error messages like that before, but it's been a long time since I last saw one, and I can't remember how I fixed it. Could you share your full debug info ( ?-Debug Info... from the Notepad++ main menu)? That might help us diagnose the source of the issue. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by cdellafera** [comment]
I figured it out and everything now complies correctly. This has to be the stupidest error ever. It turns out there was an OLD NuGet package reference from a project I worked on years ago that was preventing the build from completing correctly. I started poking around in the C# error logs and noticed an odd error in the NuGet list that seemed to have nothing to do with the current project. Sure enough, when I opened it, it referenced this long-ago deleted reference in another project! Once I deleted the reference, suddenly NuGet ran and exited without any errors and everything built correctly. I have NO idea why NuGet failing to run would have caused this particular problem. If you can figure it out, maybe you can make things more bullet proof, but honestly it's a mystery to me! Incidentally, the reason I cloned the package is to add a feature to get the current file's creation date/time and last modified date/time so that it can be added as comment text to the file being edited. Ciarán... Ciarán Anthony DellaFera, BSG, M.D. 99 Otis Street, Apt 4 Cambridge, MA 02141-1722 Mobile: +1 617.921.0682 Pronouns: He/Him/His On Aug 11, 2024, at 5:01 PM, Ciaran DellaFera ***@***.***> wrote: The dependencies folder has an x64 file so it seems unlikely I downloaded the wrong version. I tried setting the debug breakpoints, but the error occurs before then, so something is odd. This is definitely only due to this plugin. The error message references the plugin by name and removing it allows NPP to launch normally. Here's the debug information: Notepad++ v8.6.9 (64-bit) Build time : Jul 12 2024 - 05:09:25 Path : C:\Program Files\Notepad++\notepad++.exe Command Line : Admin mode : OFF Local Conf mode : OFF Cloud Config : OFF Periodic Backup : ON OS Name : Windows 10 Pro (64-bit) OS Version : 22H2 OS Build : 19045.4651 Current ANSI codepage : 1252 Plugins : BracketsCheck (1.2.2) DSpellCheck (1.5) Explorer (1.9.9) JsonTools (8) mimeTools (3.1) NppConverter (4.6) NppExport (0.4) PoorMansTSqlFormatterNppPlugin (1.6.13.31508) XMLTools (3.1.1.13) The AssemblyInfo.cs is: using System.Reflection; using System.Runtime.InteropServices; // General Information about an assembly is controlled through the following // set of attributes. Change these attribute values to modify the information // associated with an assembly. [assembly: AssemblyTitle("C# Demo plugin for Notepad++")] [assembly: AssemblyDescription("")] [assembly: AssemblyConfiguration("")] [assembly: AssemblyCompany("Mark Johnston Olson")] [assembly: AssemblyProduct("C# Demo plugin for Notepad++")] [assembly: AssemblyCopyright("Copyright © molsonkiko 2024")] [assembly: AssemblyTrademark("")] [assembly: AssemblyCulture("")] // Setting ComVisible to false makes the types in this assembly not visible // to COM components. If you need to access a type in this assembly from // COM, set the ComVisible attribute to true on that type. [assembly: ComVisible(false)] // The following GUID is for the ID of the typelib if this project is exposed to COM [assembly: Guid("2f8c343a-3fa0-47ba-b3b5-23a5757f8779")] // Version information for an assembly consists of the following four values: // // Major Version // Minor Version // Build Number // Revision // [assembly: AssemblyVersion("0.0.3.11")] [assembly: AssemblyFileVersion("0.0.3.11")] Ciarán... Ciarán Anthony DellaFera, BSG, M.D. 99 Otis Street, Apt 4 Cambridge, MA 02141-1722 Mobile: +1 617.921.0682 Pronouns: He/Him/His On Aug 10, 2024, at 4:01 PM, molsonkiko ***@***.***> wrote: There are two main possibilities that occur to me: You are building the 32-bit version of the plugin and copying it into the plugins folder of your 64-bit Notepad++. This seems unlikely, because Notepad++ would be expected to give a different error message in that situation. Some runtime error is happening as you load the plugin. I recommend building in Debug mode and setting breakpoints at the start of the Main.CommandMenuInit() method and SettingsBase(bool) method , since those are two of the first methods called when the plugin starts up. If the error happens before any of those breakpoints are hit, I'm not really sure what is happening. I've definitely seen error messages like that before, but it's been a long time since I last saw one, and I can't remember how I fixed it. Could you share your full debug info ( ?-Debug Info... from the Notepad++ main menu)? That might help us diagnose the source of the issue. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by cdellafera** [comment]
I figured it out and everything now complies correctly.

This has to be the stupidest error ever. It turns out there was an OLD NuGet package reference from a project I worked on years ago that was preventing the build from completing correctly. I started poking around in the C# error logs and noticed an odd error in the NuGet list that seemed to have nothing to do with the current project. Sure enough, when I opened it, it referenced this long-ago deleted reference in another project!

Once I deleted the reference, suddenly NuGet ran and exited without any errors and everything built correctly.

I have NO idea why NuGet failing to run would have caused this particular problem. If you can figure it out, maybe you can make things more bullet proof, but honestly it's a mystery to me!

Incidentally, the reason I cloned the package is to add a feature to get the current file's creation date/time and last modified date/time so that it can be added as comment text to the file being edited.

Ciarán...

Ciarán Anthony DellaFera, BSG, M.D.
99 Otis Street, Apt 4
Cambridge, MA 02141-1722
Mobile: +1 617.921.0682
Pronouns: He/Him/His

On Aug 11, 2024, at 5:01 PM, Ciaran DellaFera ***@***.***> wrote:


The dependencies folder has an x64 file so it seems unlikely I downloaded the wrong version.

I tried setting the debug breakpoints, but the error occurs before then, so something is odd. This is definitely only due to this plugin. The error message references the plugin by name and removing it allows NPP to launch normally.

Here's the debug information:

Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4651
Current ANSI codepage : 1252
Plugins :
    BracketsCheck (1.2.2)
    DSpellCheck (1.5)
    Explorer (1.9.9)
    JsonTools (8)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    XMLTools (3.1.1.13)

The AssemblyInfo.cs is:

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("C# Demo plugin for Notepad++")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Mark Johnston Olson")]
[assembly: AssemblyProduct("C# Demo plugin for Notepad++")]
[assembly: AssemblyCopyright("Copyright © molsonkiko 2024")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("2f8c343a-3fa0-47ba-b3b5-23a5757f8779")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("0.0.3.11")]
[assembly: AssemblyFileVersion("0.0.3.11")]

Ciarán... Ciarán Anthony DellaFera, BSG, M.D. 99 Otis Street, Apt 4 Cambridge, MA 02141-1722 Mobile: +1 617.921.0682 Pronouns: He/Him/His

On Aug 10, 2024, at 4:01 PM, molsonkiko ***@***.***> wrote:


There are two main possibilities that occur to me:

  1.  You are building the 32-bit version of the plugin and copying it into the plugins folder of your 64-bit Notepad++. This seems unlikely, because Notepad++ would be expected to give a different error message in that situation.
  2.  Some runtime error is happening as you load the plugin. I recommend building in Debug mode and setting breakpoints at the start of the Main.CommandMenuInit() method<https://github.com/molsonkiko/NppCSharpPluginPack/blob/82edb829a39426d1a2cba8d7fb6284fc07267c5c/NppCSharpPluginPack/Main.cs#L68> and SettingsBase(bool) method<https://github.com/molsonkiko/NppCSharpPluginPack/blob/82edb829a39426d1a2cba8d7fb6284fc07267c5c/NppCSharpPluginPack/PluginInfrastructure/SettingsBase.cs#L71>, since those are two of the first methods called when the plugin starts up. If the error happens before any of those breakpoints are hit, I'm not really sure what is happening.

I've definitely seen error messages like that before, but it's been a long time since I last saw one, and I can't remember how I fixed it.

Could you share your full debug info (?-Debug Info... from the Notepad++ main menu)? That might help us diagnose the source of the issue.

**Comment by molsonkiko** [comment]
@cdellafera 

Glad you were able to figure it out! Thanks for explaining how you solved the issue.

Given that this seems to be a problem with your `.csproj` file or other project files that user-written code doesn't really directly interface with, I doubt there's any easy way to improve the resilience of the plugin pack to these types of errors, so my inclination is to close this issue.

If you think of a way to help avoid this problem in the future, you're more than welcome to submit a PR with your idea.
